name: Prisma Migrate

on:
  workflow_dispatch: # ça veut dire que tu déclenches manuellement depuis GitHub

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install deps
        run: npm install

      - name: Run Prisma migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma migrate deploy
