name: Prisma Migrate

on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Test DB connectivity
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: echo "SELECT 1" | npx prisma db execute --stdin --url $DATABASE_URL

      - name: Apply migrations (deploy)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma migrate deploy

      - name: Seed database
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma db seed
